Allow for Infection 0.26.10 and drop PHP 7.4
Roave/infection-static-analysis-plugin pull request #385
Opened 2022-05-19 15:24 UTC by pamil

Infection 0.26.7 has dropped support for PHP 7.4 so Dependabot stopped updating Infection's version.

2022-05-19 16:06 UTC, Ocramius requested changes
`composer.lock` seems to be out of sync in CI 🤔

2022-05-20 10:53 UTC, Ocramius approved these changes

2022-05-20 10:55 UTC, Ocramius commented
Thanks @pamil!

2022-05-20 10:55 UTC, merged

2022-05-20 11:41 UTC, pamil commented
Thanks for the plugin and for releasing a new version 🎉