Support PHP 8.4
Roave/infection-static-analysis-plugin pull request #497
Opened 2024-05-25 11:54 UTC by staabm

2024-05-25 12:27 UTC, Ocramius requested changes
Note: I'd only merge after a green 8.4 CI run

2024-05-25 12:27 UTC, Ocramius commented on composer.json
> +        "php": "~8.1.0 || ~8.2.0 || ~8.3.0 || ~8.4.0",
`composer.lock` needs refreshing

2024-05-25 12:31 UTC, staabm commented
> Note: I'd only merge after a green 8.4 CI run

I ran it locally successfully against 8.4. :)

2024-05-25 12:33 UTC, Ocramius commented
You'd need to check the upstream laminas CI actions 👍

2024-11-21 18:12 UTC, vjik commented
How are you doing with this PR? PHP 8.4 is released, the time has come :)

2025-01-20 15:23 UTC, closed without merging